module.exports = {
  databaseUrl: 'localhost',
  databasePort: 3306,
  databaseUsername: 'root',
  databasePassword: 'imapassword',
  debug: true,
  apiHost: 'localhost',
  apiPort: 3000,
  databaseDb: 'centcom',
  frontEndUrl: 'localhost',
  frontEndPort: 8080,
  apiSSL: false,
  apiSSLKeyFile: undefined,
  apiSSLCertFile: undefined,
  apiSSLKeyPassphrase: undefined,
  frontEndSSL: false,
};